name: Build

on:
  push:
    branches: [main-oxi]
  pull_request:
    branches: [main-oxi]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, x86, arm64]

    steps:
      - uses: actions/checkout@v7

      - uses: microsoft/setup-msbuild@v3

      - name: Restore dependencies and build
        run: msbuild src/Shell.sln /m /restore /p:RestorePackagesConfig=true /p:Configuration=release /p:Platform=${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: shell-${{ matrix.platform }}
          path: |
            src/bin/**
            !src/bin/*.lib
            !src/bin/*.exp
            !src/bin/*.wixpdb
            !src/bin/ca.dll
          if-no-files-found: error
